[package]
name = "halo2-shplonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
rand = "0.8"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"

halo2_gadgets = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_04_20" } # not optional for now
pasta_curves = "0.5"
ff = "0.13"

snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier.git" , default-features = false }
snark-verifier-sdk = { git = "https://github.com/privacy-scaling-explorations/snark-verifier.git" }

# system_halo2
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_04_20" } # not optional for now
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = "0.3.2" }  # must be same version as in halo2_proofs
halo2-common = {path = "../halo2-common"}

# loader_halo2
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2023_04_20", package = "ecc", optional = true }
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon", tag = "v2023_04_20", optional = true }

# loader_evm
ethereum-types = { version = "0.14", default-features = false, features = [
    "std",
], optional = true }

ark-std = { version = "0.3.0", features = ["print-trace"] }
paste = "1.0.7"
pprof = { version = "0.11", features = ["criterion", "flamegraph"] }
criterion-macro = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }

[dev-dependencies]
flate2 = "1.0"
hex = "0.4.3"
sha2 = "0.10.7"
tracing-test = "0.2.4"
expect-test = "1.4.1"
anyhow = "1.0.72"
tap = "1.0.1"
tracing-texray = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[[bench]]
name = "poseidon"
harness = false

[features]
default = ["loader_halo2", "loader_evm", "derive_serde", "display"]
display = []
loader_evm = ["snark-verifier/loader_evm", "dep:ethereum-types"]
loader_halo2 = [
    "snark-verifier/system_halo2",
    "snark-verifier/loader_halo2",
    "dep:halo2_wrong_ecc",
    "dep:poseidon",
]
parallel = ["snark-verifier/parallel"]
derive_serde = ["snark-verifier/derive_serde", "halo2curves/derive_serde"]
halo2_circuit_params = ["snark-verifier/halo2_circuit_params"]
